name: mwidgets
description: Contains a custom widgets like MText, MDropdown, MFileImage, MNetworkImage, MLottie, MSvg,
  MBouncingButton, MRating, MPinPut, MScroll, MTextFiled, MRangeItemWidget, MRadioItemWidget and
  others
version: 0.0.2
homepage: https://github.com/ibrahimnashat/mwidgets.git

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  eitherx: ^1.0.3
  get_it: ^7.2.0
  equatable: ^2.0.5
  injectable: ^2.1.2
  flutter_bloc: ^8.1.3
  localization: ^2.1.0
  bouncing_widget: ^2.0.0
  pinput: ^2.2.31
  flutter_rating_bar: ^4.0.1
  lottie: ^2.2.0
  easy_image_viewer: ^1.2.0
  flash: ^3.0.3+5
  square_percent_indicater: ^0.1.0
  skeletons: ^0.0.3
  cupertino_range_slider_improved: ^2.0.1
  flutter_gen: ^5.3.1
  phone_number: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/
